export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_PROFILE = 'AUTH_PROFILE';

export const REQUEST_BEGIN = 'REQUEST_BEGIN';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_END = 'REQUEST_END';

export const WORKSPACE_CHANGE = 'WORKSPACE_CHANGE';
export const WORKSPACE_LIST = 'WORKSPACE_LIST';
export const WORKSPACE_CARD = 'WORKSPACE_CARD';
export const BRANCH_CHANGE = 'AUTH_BRANCH';

export const DICT_PERMISSION = 'DICT_PERMISSION';
export const DICT_GROUPS = 'DICT_GROUPS';
export const DICT_USERS = 'DICT_USERS';
export const DICT_ROLES = 'DICT_ROLES';
export const DICT_BANKS = 'DICT_BANKS';
export const DICT_CAR_MARKS = 'DICT_CAR_MARKS';
export const DICT_CAR_MODELS = 'DICT_CAR_MODELS';
export const DICT_CAR_COLORS = 'DICT_CAR_COLORS';
export const DICT_MACHINERY_MARKS = 'DICT_MACHINERY_MARKS';
export const DICT_MACHINERY_MODELS = 'DICT_MACHINERY_MODELS';
export const DICT_MACHINERY_COLORS = 'DICT_MACHINERY_COLORS';
export const DICT_CATEGORIES = 'DICT_CATEGORIES';
export const DICT_CATEGORIES_CAR = 'DICT_CATEGORIES_CAR';
export const DICT_CATEGORIES_GOOD = 'DICT_CATEGORIES_GOOD';
export const DICT_CATEGORIES_GOLD = 'DICT_CATEGORIES_GOLD';
export const DICT_CATEGORIES_MACHINERY = 'DICT_CATEGORIES_MACHINERY';
export const DICT_ACCOUNTS = 'DICT_ACCOUNTS';
export const DICT_PURITIES = 'DICT_PURITIES';
export const DICT_EVENT_CODES = 'DICT_EVENT_CODES';
export const DICT_EXPENSE_GROUPS = 'DICT_EXPENSE_GROUPS';
export const DICT_EXPENSE_TYPES = 'DICT_EXPENSE_TYPES';

export const RECEIVER_CHANGE = 'RECEIVER_CHANGE';
export const RECEIVER_LIST = 'RECEIVER_LIST';
export const RECEIVER_CARD = 'RECEIVER_CARD';

export const INSURANCE_CHANGE = 'INSURANCE_CHANGE';
export const INSURANCE_LIST = 'INSURANCE_LIST';
export const INSURANCE_CARD = 'INSURANCE_CARD';